### ISSUE TITLE
Possible Feature request?

### ISSUE THREAD

**Issue by Thistheway7** [Jabb0/CatchAllBird#1]
Hello!

First of all i want to thank you for the great Thunderbird addon! 

I really love that it automatically creates a new thunderbird identity and that it selects the correct address. But i don't want the Emails sorted to the folders. Could you possibly add a setting to turn off the automatic creating of a folder? 

Thank you very much!

**Comment by Jabb0** [comment]
Hello,

thank you for the input.
This is a great idea. I will have a look.

**Comment by Jabb0** [comment]
Published as version 1.0.5. 

Have fun :)

**Comment by Thistheway7** [comment]
Thank you very much! That was extremely fast! Now the addon behaves exaclty how i need it!
