### ISSUE TITLE
catchall bird

### ISSUE THREAD

**Issue by stevesardo** [Jabb0/CatchAllBird#10]
added this and set default SMTP but not working
![IMG_4546](https://user-images.githubusercontent.com/60269835/209139309-73324a58-6a5e-419d-ad88-11d26126949f.jpg)
![IMG_4547](https://user-images.githubusercontent.com/60269835/209139310-862401f0-9168-47af-890c-1df924420ce1.jpg)
![IMG_4548](https://user-images.githubusercontent.com/60269835/209139312-c596b777-ad60-4516-be2c-48c250932859.jpg)

**Comment by Jabb0** [comment]
Hi,
can you give some details on what is not working, please?

The last picture is blurry, but if the checkbox is at the correct domain the config should be fine.

**Comment by LionelHolt** [comment]
[How to Take a Screenshot on a Windows PC](https://www.wikihow.com/Take-a-Screenshot-in-Microsoft-Windows) 🙂
