### ISSUE TITLE
Automatically created identities are truncated

### ISSUE THREAD

**Issue by knilde** [Jabb0/CatchAllBird#3]
I have three imap-accounts and following settings active:
Create Folders automatically = false
Create Identities automatically = true

Examples for sender-addresses, automatically created by plugin:
  1) al_paypal1@mydomain.de => paypal1@mydomain.d@
  2) al_gkv@mydomain.de => al_gkv@mydomain.d@
  3) al_test123@mydomain.de => test123@mydomain.de
  4) 0123abc@mydomain.de =>0123abc@mydomain.de

Example 1, 2 and 3 shows missing prefix.
Example 3 shows no @ at the but also the prefix is missing.
Example 4 shows NO error. The source mail has not the prefix (al_).
Maybe the underscore (_) I use as prefix is the problem?

I updated Thunderbird yesterday (minor update to version 91.8.1). This could be relevant too.

**Comment by Jabb0** [comment]
Thank you for the report. I will have a look.

**Comment by Jabb0** [comment]
I know why the missing prefix is happening. This is an easy fix.

The trailing @ is interesting as it does not happen for me.
Could you check if the domain name in the AddOn settings (where you enable it for specific domains) is shown correctly?

**Comment by knilde** [comment]
Thanks for your quick responce.

I deleted all identities upon issue-opening that were generated by plugin.
Since that 4 new identities were generated by plugin.
One new created (address) was example #1 with trailing @ but I can not see anymore trainling @.
Position of the @ was in the mailaddress itself. Not in the title of the identity.
If it reoccurs I will let you know.

**BTW thanks for that plugin! The identity-part is a unique feature, I found nowhere else.**
Was waiting for that a long time... puh! :-)

**Feature-Request:**
Another similar feature may be YOUR thing to code:
"Automatically create identity when an temporary, user definded idententy is defined (compose new mail>options>user defined sender...)"
or in short words:
Whenever I send a mail with unknown **senderaddress**, create identity automatically.

What do you think? A useful feature(-request)?

**Comment by Jabb0** [comment]
Thanks for the feedback! Glad to see people enjoy it.

I will provide an updated version that allows "_" in emails today.

Regarding the **feature request:**
Isn't it enough that the plugin creates the identity the email gets answered? So you get the identity once the prefix is used in a conversation.
Creating a identity at this point makes sense if you plan to reuse it without getting an answer. But how often does that happen?
